### ISSUE TITLE
How to apply patches 

### ISSUE THREAD

**Issue by tami5** [06kellyjac/suckless-git-overlay#18]
Hey @06kellyjac not sure if this is out of the scope or not, but using this flake how could one apply a patch?

Thanks

**Comment by 06kellyjac** [comment]
I'll get you a snippet later but overlayAttrs then set patches = [ your stuff here ] should work fine

**Comment by tami5** [comment]
Thanks @06kellyjac

**Comment by 06kellyjac** [comment]
https://nixos.wiki/wiki/St#Patching

LMK how it goes

**Comment by 06kellyjac** [comment]
If there are issues, if they occur on nixpks-unstable I'll try push a fix there. Or if its just on master releases here ill fix it here
